apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    osm-service: osm-zookeeper
  name: osm-zookeeper
spec:
  ports:
  - name: "2181"
    port: 2181
    targetPort: 2181
  selector:
    osm-service: osm-zookeeper
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    osm-service: osm-zookeeper
  name: osm-zookeeper
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        osm-service: osm-zookeeper
    spec:
      containers:
      - image: wurstmeister/zookeeper:latest
#        livenessProbe:
#          exec:
#            command:
#            - "echo stat | nc 127.0.0.1 2181"
#          failureThreshold: 3
#          periodSeconds: 20
#          timeoutSeconds: 20
        name: osm-zookeeper
        resources: {}
      restartPolicy: Always
status: {}
